const imgBreakDown = {
  typeOutline: {
    BBQ: {
      prodType: "Baby Quilts",
      prodDesc: `<p>
      A MUST FOR THAT PRECIOUS LITTLE ONE IN YOUR LIFE..&nbsp; These quilts are just perfect for the crib, or to send along to day care or pre school. Made by hand, each quilt has eight squares of machine embroidery. The back of the quilt is flannel for warmth. All fabric is 100% cotton with Warm &amp; Natural batting inside. The binding is hand sewn on the back side.&nbsp; Fabric has been prewashed. Quilts are about 37" wide X45"long.</p><p>Can't find the colors or embroidery designs&nbsp;you want?&nbsp; Call or e-mail me. Special orders gladly accepted.</p><p>Please allow 3 weeks for special orders.</p><p><span style="font-size: 24px"><span style="color: #0000ff"><span style="background-color: #00ff00">&nbsp; FREE SHIPPING ON ALL BABY QUILTS</span></span></span></p><p>&nbsp;</p><p></p><p id="note">*Please note: Contrasting fabric may vary from image shown*</p>`,
      prodPrice: 0,
      prodImgLocation: ""
    },
    BKP: {
      prodType: "Backpack",
      prodDesc: "Self explanatory",
      prodPrice: 35,
      colors: ["charcoal", "black", "navy", "royal blue", "red"],
      prodImgLocation: ""
    },
    BPB: {
      prodType: "Baked Potato Bag",
      prodDesc: `<p align="left"><b><font color="#800000" face="Verdana" size="5">THE BEST THING TO HAPPEN TO BAKED POTATOES!!!</font></b></p><p align="left"><b><font color="#111111" face="Verdana">Tired of over cooked ends on your microwave baked potatoes? Long for baked potatoes to be fluffy like when you used to bake them in the oven? </font></b></p><p align="left"><font color="#111111" face="Verdana">When you use my baked potato bag to bake your potatoes in the microwave, your potato will come out fluffy and evenly cooked just as if you baked them in the oven and used all that electricity. These bags are not only wonderful for potatoes, you can also use them to cook yams, corn on the cob, squash, sweet potatoes, artichokes and more.</font></p><p align="left"><span style="color: #0000ff"><font face="Verdana"><span style="font-size: 20px"><span style="background-color: #00ff00">&nbsp; FREE SHIPPING ON ORDERS $60.00 AND OVER.</span></span></font></span></p>`,
      prodPrice: 10,
      prodImgLocation: "BakedPotatoBag.jpg"
    },
    BWL: {
      prodType: "Large Bowl Wrap",
      prodDesc: `<p style="font-size: 20px">The perfect companion for that bowl of soup or hot cereal you heat in the microwave. Never burn your hands again trying to pick up that bowl. Like ice cream? Tired of freezing your hands?&nbsp;&nbsp;Sit your dish in THE BOWL WRAP! Entertaining?&nbsp;Set that bowl of candy or peanuts in THE BOWL WRAP!&nbsp;Each&nbsp;BOWL WRAP&nbsp;is&nbsp;handmade of 100% cotton, shaped like a bowl and&nbsp;pre-washed to prevent shrinkage.&nbsp;Pick from the many selections below.&nbsp;</p><p><span style="font-size: 20px"><span style="font-size: 24px"><span style="color: #0000ff"><span style="background-color: #00ff00">&nbsp; FREE SHIPPING ON ORDERS $60.00 AND OVER.</span></span></span></span></p><p id="note">*Please note: Contrasting fabric may vary from image shown*</p>`,
      prodPrice: 20,
      prodImgLocation: "BowlWrap.jpg"
    },
    BWS: {
      prodType: "Small Bowl Wrap",
      prodDesc: `<p style="font-size: 20px">The perfect companion for that bowl of soup or hot cereal you heat in the microwave. Never burn your hands again trying to pick up that bowl. Like ice cream? Tired of freezing your hands?&nbsp;&nbsp;Sit your dish in THE BOWL WRAP! Entertaining?&nbsp;Set that bowl of candy or peanuts in THE BOWL WRAP!&nbsp;Each&nbsp;BOWL WRAP&nbsp;is&nbsp;handmade of 100% cotton, shaped like a bowl and&nbsp;pre-washed to prevent shrinkage.&nbsp;Pick from the many selections below.&nbsp;</p><p><span style="font-size: 20px"><span style="font-size: 24px"><span style="color: #0000ff"><span style="background-color: #00ff00">&nbsp; FREE SHIPPING ON ORDERS $60.00 AND OVER.</span></span></span></span></p>`,
      prodPrice: 10,
      prodImgLocation: "BowlWrap.jpg"
    },
    CAP: {
      prodType: "Caps",
      prodDesc: `<p><span style="font-size: 18px">Time to replace that worn out cap??&nbsp; Why not wear one with man's best friend on it.&nbsp; Two styles to choose from, like the unstructured type, order CP78, for those that like the firmer cap, order the structured CP80.&nbsp; 100% cotton twill. Both styles are adjustable.</span><span style="font-size: 18px">Four colors to choose from, hunter green, red, blue and khaki.&nbsp; These caps make a great Father's Day gift. If you don't see you favorite dog breed, just give us a call or send an e-mail.</span></p><p>&nbsp;</p><p><span style="font-size: 18px"><span style="font-size: 24px"><span style="color: #0000ff"><span style="background-color: #00ff00">&nbsp;FREE SHIPPING ON ORDERS $60.00 AND OVER</span></span></span></span></p>`,
      prodPrice: 20,
      colors: [],
      prodImgLocation: "Cap2.jpg"
    },
    COM: {
      prodType: "Computer Briefcase",
      prodDesc: "",
      prodPrice: 50,
      colors: ["heather grey", "navy"],
      prodImgLocation: ""
    },
    DOQ: {
      prodType: "Dog Quilts",
      prodDesc: `<p>Just in time for the Holidays!!&nbsp; The perfect gift for the dog or cat lover on your list. Makes a great gift for that pet in your life too.&nbsp; Each quilt is about 37"wide X 45"long,&nbsp;just right for most dogs or a lap quilt. There&nbsp;are eight squares of machine embroidery designs of the Dog Breed of your choice (if available). The reverse side of the quilt is flannel.&nbsp; All fabric is 100% cotton that has been pre-washed by us before the quilt is made. Each quilt is made in the USA by us.&nbsp; Custom quilts are welcome, so if you have more then one breed of dog, we can put more then one on a quilt. You can also choose colors.&nbsp; We try to have a good stock on hand, custom quilts will take up to 3 weeks to finish. Larger quilts available on request.&nbsp; Please call 360-599-1816 or e-mail, <a href="mailto:embroidery@quilts.ws">embroidery@quilts.ws</a> for special orders.&nbsp; GO TO THE "TOTE BAG" PAGE ON LEFT TO SEE THE DOG AND CAT DESIGNS</p><p>
      &nbsp;</p><p><span style="font-size: 24px"><span style="color: #0000ff"><span style="background-color: #00ff00">FREE SHIPPING ON ALL DOG QUILTS</span></span></span></p>  <p></p><p id="note">*Please note: Contrasting fabric may vary from image shown*</p><u><b><i><font face="Verdana" size="4">Australian Shephard</font></i></b></u>`,
      prodPrice: 95,
      prodImgLocation: ""
    },
    FAB: {
      prodType: "Fabric",
      prodImgLocation: ""
    },
    GRB: {
      prodType: "Grocery Bag AKA Tote Bag",
      prodDesc: `<p>Looking for a "tote bag" that won't let you down?? Look no further. Our bag is made of durable water resistant 600 demier polyester fabric, the inside can be wiped out with a damp cloth should something spill. Two small inside pockets and a water bottle pocket on the outside. Tired of your tote bag falling over and everything spilling out??&nbsp;&nbsp; Bag measures 14" wide X 12" high,&nbsp;6 1/2" deep.. With your favorite pet embroidered on front you can bring it along where ever you go. Comes in your choice of colors listed below. If you don't see your dog breed, please e-mail me. Most breeds available. Don't want a dog on this bag, special orders welcome. <span style="font-size: 16px">T-SHIRTS, SWEATSHIRTS, HOODIES ARE AVAILABLE. PLEASE CONTACT US BY PHONE OR E-MAIL FOR COLORS ETC.</span></p><p><span style="color: #0000ff"><span style="font-size: 16px">&nbsp;BAGS ARE ONLY $20.00 EACH. DESIGNS WILL VARY IN SIZE&nbsp;&nbsp; </span></span></p><p><span style="font-size: 16px"><span style="font-size: 24px"><span style="color: #0000ff"><span style="background-color: #00ff00">&nbsp;&nbsp; FREE SHIPPING ON ORDERS $60.00 AND OVER</span></span></span></span></p>`,
      prodPrice: 20,
      colors: ["red", "royal blue", "carolina blue", "navy", "lime green", "kelly green", "purple", "lavender", "light pink", "hot pink", "black", "charcoal grey", "turquoise", "tangerine", "stone"],
      prodImgLocation: ""
    },
    HOO: {
      prodType: "Hoodie",
      prodDesc: "Regular Hoodie",
      prodPrice: 40,
      colors: ["red", "royal blue", "heather grey", "purple", "lavender", "forest green"],
      prodImgLocation: ""
    },
    HOZ: {
      prodType: "Zipper Hoodie",
      prodDesc: "Hoodie with a zipper",
      prodPrice: 45,
      colors: ["red", "royal blue", "heather grey", "purple", "lavender", "forest green"],
      prodImgLocation: ""
    },
    OVM: {
      prodType: "Oven Mitt",
      prodDesc: `<p><u><b><i><font face="Verdana" size="5">ONE SIZE FITS ALL!!!&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</font></i></b></u></p><p><font face="Verdana">Finally an oven mitt that fits everyone, the perfect size. Well insulated to protect you from the heat.</font></p><p><font face="Verdana"><span style="font-size: 22px"><span style="font-size: 24px"><span style="color: #0000ff"><span style="background-color: #00ff00">&nbsp; FREE SHIPPING ON ORDERS $60.00 AND OVER</span>.</span></span></span></font></p><p></p><p id="note">*Please note: Contrasting fabric may vary from image shown*</p>`,
      prodPrice: 10,
      prodImgLocation: "OvenMitt.jpg"
    },
    PLT: {
      prodType: "Plate Wrap",
      prodDesc: "Use for microwaving plates",
      prodPrice: 25,
      prodImgLocation: ""
    },
    SLN: {
      prodType: "Sling",
      prodDesc: "",
      prodPrice: 15,
      colors: ["red", "royal blue", "lime green", "navy", "black"],
      prodImgLocation: ""
    },
    SWT: {
      prodType: "Sweatshirt",
      prodDesc: "",
      prodPrice: 30,
      colors: ["red", "royal blue", "heather grey", "purple", "lavender", "forest green"]
    },
    TLB: {
      prodType: "Tortilla Bags",
      prodDesc: `<p><span style="font-size: 22px">The perfect bag for heating your tortilla's or rolls in the microwave.&nbsp; Bag is 10" across so the small and medium tortilla's fit perfectly,&nbsp;you can then&nbsp;put the bag on the table to keep them warm. Can also be used for that extra waffle or pancakes. Bags are all handmade from 100% cotton that has been prewashed to prevent shrinkage. Lots of designs to choose from.</span></p><p>&nbsp;</p><p><span style="font-size: 22px"><span style="font-size: 24px"><span style="color: #0000ff"><span style="background-color: #00ff00">&nbsp; FREE SHIPPING ON ORDERS $60.00 AND OVER</span></span></span></span></p>`,
      prodPrice: 7.50,
      prodImgLocation: "TortillaBag.jpg"
    },
    TOW: {
      prodType: "Kitchen Towel",
      colors: ["white", "stone", "blue", "light moss", "dark moss"],
      prodImgLocation: ""
    },
    TSL: {
      prodType: "Long Sleeve T-Shirt",
      prodDesc: "",
      prodPrice: 25,
      colors: ["red", "royal blue", "heather grey", "purple", "lavender", "forest green"],
      prodImgLocation: ""
    },
    TSS: {
      prodType: "Short Sleeve T-Shirt",
      prodDesc: "",
      prodPrice: 15,
      colors: ["red", "royal blue", "heather grey", "purple", "lavender", "forest green"],
      prodImgLocation: ""
    },
    VES: {
      prodType: "Vest",
      prodDesc: "",
      prodPrice: 30,
      colors: ["red", "royal blue", "navy blue"],
      prodImgLocation: ""
    },
    ZZT: {
      prodType: "Zipper Tote Bag",
      prodDesc: "Your all in one tote bag with a zipper for secure transportation.",
      prodPrice: 10,
      colors: ["red", "royal blue", "hot pink", "black"],
      prodImgLocation: ""
    }
  },
  imgSubCat: {
    abd: "American Bull Dog",
    afg: "Afghan",
    air: "Airdale",
    aki: "Akita",
    asc: "Australian Cattle Dog",
    atr: "Australian Terrier",
    aus: "Australian Shepherd",
    baj: "Basenji",
    bas: "Basset",
    bch: "Bluetick Coon Hound",
    bea: "Beagle",
    bed: "Bedlington Terrier",
    bel: "Belgian Tervuren",
    ber: "Bernese Mountain",
    bic: "Bichon",
    bir: "Birds",
    bld: "Bloodhound",
    bls: "Belgian Sheepdog",
    blt: "Bull Terrier",
    bod: "Border Terrier",
    bor: "Borzo",
    bos: "Boston Terrier",
    bov: "Bouvier Des Flandres",
    box: "Boxer",
    brc: "Border Collie",
    brd: "Bearded Collie",
    brr: "Briard",
    brt: "Brittany Spaniel",
    bru: "Brussels Griffen",
    btc: "Black & Tan Coon Hound",
    bug: "Bugs and Frogs",
    bul: "English Bull",
    cah: "Catahoula",
    can: "Cane Corso",
    cat: "Cats",
    cdo: "Cats and Dogs",
    chc: "Chinese Crested",
    che: "Chesapeake Bay Retriever",
    chi: "Chihuahua",
    cho: "Chow Chow",
    clb: "Clumber Spaniel",
    col: "Collie",
    cor: "Corgi",
    cos: "Cocker Spaniel",
    cot: "Coton de Tuleau",
    dal: "Dalmation",
    ddt: "Dandie Dinmount Terrier",
    dob: "Doberman",
    dox: "Dachshund",
    egs: "Old English Sheep Dog",
    eng: "English Setter",
    esk: "American Eskimo",
    fbl: "French Bulldog",
    fdk: "Food",
    flr: "Flowers",
    flt: "Flat Coated Retriever",
    fox: "Fox Terrier",
    frm: "Farm",
    gol: "Golden Retriever",
    gor: "Gordon Setter",
    grd: "Great Dane",
    grp: "Great Pyranees",
    grs: "German Shorthair",
    gry: "Greyhound",
    gsm: "Great Swiss Mountain Dog",
    hav: "Havanese",
    hol: "Holidays",
    hus: "Husky",
    ice: "Icelandic Sheepdog",
    irh: "Irish Setter",
    irw: "Irish Water Spaniel",
    itg: "Italian Greyhound",
    iwh: "Irish Wolfhound",
    jrt: "Jack Russel Terrier",
    jpc: "Japanese Chin",
    kcs: "Cavalier King Charles Spaniel",
    ker: "Kerry Blue Terrier",
    kes: "Keeshound",
    lab: "Labrador",
    lad: "Labradoodle",
    lag: "Lagotto Romagnolo",
    lak: "Lakeland Terrier",
    leo: "Leonberger",
    lgm: "Large Munsterlander",
    lhp: "Lhasa Apso",
    mal: "Maltese",
    mas: "Mastiff",
    mil: "Military",
    min: "Min Pin (Miniature Doberman)",
    mis: "Misc",
    mor: "Morkie",
    nat: "Nautical",
    new: "Newfoundland",
    nor: "Norwich Terrier",
    nov: "Nova Scotia Duck Toller",
    pap: "Papillon",
    pek: "Pekinese",
    pic: "Picard",
    pit: "Pit Bull",
    plh: "Plott Hound",
    pod: "Poodle",
    pom: "Pomeranian",
    por: "Portuguese Water Dog",
    pug: "Pug",
    pul: "Hungerian Puli",
    rat: "Rat Terrier",
    rod: "Rhodesian Ridgeback",
    rot: "Rottweiler",
    sal: "Saluki",
    sam: "Sanoyed",
    sch: "Schnauzer",
    sci: "Schipperke",
    sco: "Scottie",
    sha: "Shar pei",
    shb: "Shiba Inu",
    she: "German Shepherd",
    shi: "Shih Tzu",
    shl: "Sheltie",
    sil: "Silky Terrier",
    smc: "Smooth Collie",
    spr: "English Spring Spaniel",
    stb: "St Bernard",
    stf: "Staffordshire Terrier",
    tib: "Tibetan Terrier",
    tre: "Treeing Walker Hound",
    vis: "Visla",
    wdl: "Wild Animals",
    wei: "Weimeraner",
    whi: "West Highland Terrier",
    wht: "Wheaten Terrier",
    wip: "Whippert",
    wfx: "Wire Fox Terrier",
    wss: "Welch Springer Spaniel",
    yor: "Yorkshire"
  },
  colors: {
    red: "Red",
    gold: "Gold",
    blue: "Blue",
    charcoal: "Charcoal",
    purple: "Purple",
    lavender: "Lavender",
    hotPink: "Hot Pink",
    cream: "Cream",
    navy: "Navy",
    green: "Kelly Green"
  }
};

export default imgBreakDown;